# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 656e6db25e92a9607021786534c756ad12d7af4ed3e87047f1486f828da89cdbd08043345f9daf4ed3649710fbcf3c6540f549175aac86837dd8f2f9011d660c

test:
  secret_key_base: bc97364fdc649ff0079de444b775fbff7a46c76c47596f20f449e1c0fe64421dc3aa714c58414f450dc250dcf8fdd4dfe9ee486bba3281b1bc6983f156347ed4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
